### ISSUE TITLE
Spawners avec effet éponges

### ISSUE THREAD

**Issue by Thom-exe** [ServeurHydeos/WipeMC#22]
Que les spawners repoussent l’eau comme une éponge

**Comment by Acenox** [comment]
On va essayer de le refaire, mais à noter que c'est à cause de ce système qu'on a eu des problèmes de TPS avec l'eau.

**Comment by Acenox** [comment]
Bon, j'ai essayé de le refaire, et clairement c'est juste impossible.
J'ai tout testé, mais clairement pendant la grace, c'est juste impossible, car cela consomme trop côté CPU/RAM (car à chaque écoulement de l'eau, il faut check s'il y a un spawner ou non).
