### ISSUE TITLE
Chunk collector

### ISSUE THREAD

**Issue by Thom-exe** [ServeurHydeos/WipeMC#41]
Un item qui récupère les items dans le chunk (pas tous, ceux des drop des mobs), genre des qu’ils meurent au lieu de drop par terre ça va dans le collector hein pas toutes les 15sec.
Et après en clic droit sur le collector on peut ouvrir un gui ou on voit la quantité de chaque items qu’on a et quand on clique sur les émeraudes par exemple ça vend, sur la tnt ça met sans la fbank

**Comment by Acenox** [comment]
J'ai commencé le développement du plugin

**Comment by Acenox** [comment]
Le système fonctionne +/- correctement pour les émeraudes, il reste encore des bugs avec les creepers.

**Comment by Acenox** [comment]
Terminé.
